apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nt5bv2r3x-nodejs
  janus-idp.io/tekton: nt5bv2r3x-nodejs
  backstage.io/kubernetes-id: nt5bv2r3x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nt5bv2r3x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
